CounterfactualMedicalIterableDataset_ver1:
  dataset_names:
    counterfactual_train:
    - counterfactual_cxr_chexpertplus_train
    - counterfactual_cxr_mimic_cxr_train
  image_transform_args:
    image_stride: 16
    max_image_size: 1024
    min_image_size: 512
  vit_image_transform_args:
    image_stride: 14
    max_image_size: 980
    min_image_size: 378
    max_pixels: 2_007_040
  weight:
    counterfactual_train: 10   
  num_used_data:
    counterfactual_train: [0, 0]
  is_mandatory: true
  shuffle_lines: True
  shuffle_seed: 42

